name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Static Code Analysis with pylint
      run: |
        pylint BuyingModule/ DaoModule/ EmailModule/ ScraperModule/ TimeModule/ TokenManagementModule/ UI_Module/ main.py transactions.py
    - name: Static Code Analysis with flake8
      run: |
        flake8 BuyingModule/ DaoModule/ EmailModule/ ScraperModule/ TimeModule/ TokenManagementModule/ UI_Module/ main.py transactions.py
    - name: Static Type Checking with mypy
      run: |
        mypy BuyingModule/ DaoModule/ EmailModule/ ScraperModule/ TimeModule/ TokenManagementModule/ UI_Module/ main.py transactions.py
    - name: Run Unit Tests
      run: |
        pytest